# [Subscription rules]
DEFAULT_SEARCH_DAY_LIMIT: int = 3
LITE_SEARCH_DAY_LIMIT: int = 10
PREMIUM_SEARCH_DAY_LIMIT: int = 100

QUESTIONS_LIMIT_START: int = 1  # при регистрации
DEFAULT_QUESTIONS_DAY_LIMIT: int = 0
LITE_QUESTIONS_DAY_LIMIT: int = 10
PREMIUM_QUESTIONS_DAY_LIMIT: int = 50

# [платежные пакеты для запросов]
# SMALL packet
SMALL_PACKET_SEARCH: int = 10
SMALL_PACKET_QUESTIONS: int = 3
# MEDIUM packet
MEDIUM_PACKET_SEARCH: int = 20
MEDIUM_PACKET_QUESTIONS: int = 5
# BIG PACKET
BIG_PACKET_SEARCH: int = 50
BIG_PACKET_QUESTIONS: int = 15
# GOD PACKET
GOD_PACKET_SEARCH: int = 200
GOD_PACKET_QUESTIONS: int = 100

# [ API rules ]
MIN_DAYS_TO_UPDATE_DRUG: int = 60

# [ COSTS ]
NEW_DRUG_COST: int = 1
UPDATE_DRUG_COST: int = 1

# [ VARIABLES ]
ASSISTANT_ANSWER_DRUG_COUNT_PER_PAGE: int = 3

# [ ADMIN ]
ADMINS_TG_ID = [
    "1257313065"
]
