version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  fastapi:
    build: .  # Использует Dockerfile из текущей директории
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python3 asgi.py
    environment:
      DEBUG: 'False'  # с докера дебага нет
      INTERNAL_API_URL: http://fastapi:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s
    volumes:
      - ./alembic:/drug_search/alembic
      - ./alembic.ini:/drug_search/alembic.ini
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  arq_worker:
    build: .
    container_name: worker
    env_file:
      - .env
    environment:
      - DEBUG=false  # с докера дебага нет
      - PYTHONUNBUFFERED=1  # Это важно для логирования в Docker
      - LOG_LEVEL=INFO
      - INTERNAL_API_URL=http://fastapi:8000
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      fastapi:
        condition: service_healthy
    command: arq drug_search.infrastructure.arq_config.WorkerSettings
    restart: unless-stopped
  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    environment:
      - DEBUG=false  # с докера дебага нет
      - INTERNAL_API_URL=http://fastapi:8000
    depends_on:
      fastapi:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python3 drug_search/bot/bot_app.py
    restart: unless-stopped

volumes:
  pg_data:
    name: pg_data
  redis_data:
    name: redis_data