"""extend field lock on model pathways

Revision ID: 058b34c6fc72
Revises: 1d1ecac6f300
Create Date: 2025-09-17 18:14:06.518896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058b34c6fc72'
down_revision = '1d1ecac6f300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_dosages', 'route',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_comment='parental/topical/other',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'method',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_comment='intravenous/intramuscular/eye_drops/skin/nasal/peroral/inhalation/rectal/vaginal',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'half_life',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_comment='период полувыведения',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'duration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_comment='продолжительность действия',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'binding_affinity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'affinity_description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'activation_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('drug_pathways', 'pathway',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'effect',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_pathways', 'effect',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'pathway',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'activation_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('drug_pathways', 'affinity_description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drug_pathways', 'binding_affinity',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('drug_dosages', 'duration',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_comment='продолжительность действия',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'half_life',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_comment='период полувыведения',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_comment='intravenous/intramuscular/eye_drops/skin/nasal/peroral/inhalation/rectal/vaginal',
               existing_nullable=True)
    op.alter_column('drug_dosages', 'route',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_comment='parental/topical/other',
               existing_nullable=True)
    # ### end Alembic commands ###
