"""ref tokens

Revision ID: 0da8fb4f995d
Revises: 448e9991b2b6
Create Date: 2025-11-17 13:28:33.545255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0da8fb4f995d'
down_revision = '448e9991b2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_tokens', sa.Integer(), server_default='0', nullable=False, comment='Оставшиеся запросы на поиск препов'))
    op.add_column('users', sa.Column('used_tokens', sa.Integer(), server_default='0', nullable=False, comment='Количество использованных запросов в общем'))
    op.add_column('users', sa.Column('tokens_last_refresh', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='последний сброс счётчика'))
    op.drop_column('users', 'requests_last_refresh')
    op.drop_column('users', 'used_requests')
    op.drop_column('users', 'allowed_search_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_search_requests', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False, comment='Оставшиеся запросы на поиск препов'))
    op.add_column('users', sa.Column('used_requests', sa.INTEGER(), autoincrement=False, nullable=False, comment='Количество использованных запросов в общем'))
    op.add_column('users', sa.Column('requests_last_refresh', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='последний сброс счётчика'))
    op.drop_column('users', 'tokens_last_refresh')
    op.drop_column('users', 'used_tokens')
    op.drop_column('users', 'allowed_tokens')
    # ### end Alembic commands ###
