"""фикс залупа

Revision ID: 111ee4c98a4f
Revises: a9d6d037f4c8
Create Date: 2025-08-12 18:09:21.323944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111ee4c98a4f'
down_revision = 'a9d6d037f4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'drugs', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drugs', type_='unique')
    op.drop_column('allowed_drugs', 'drug_name_ru')
    # ### end Alembic commands ###
