"""ref metabolism 3

Revision ID: 1952d69f4cdb
Revises: 1d70d8ebc154
Create Date: 2025-11-07 00:28:28.251542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1952d69f4cdb'
down_revision = '1d70d8ebc154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_dosages', 'duration')
    op.drop_column('drug_dosages', 'onset')
    op.drop_column('drug_dosages', 'half_life')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_dosages', sa.Column('half_life', sa.VARCHAR(length=150), autoincrement=False, nullable=True, comment='период полувыведения'))
    op.add_column('drug_dosages', sa.Column('onset', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="<Время начала действия (например, 'немедленно'). Только для intramuscular/intravenous/peroral>"))
    op.add_column('drug_dosages', sa.Column('duration', sa.VARCHAR(length=150), autoincrement=False, nullable=True, comment='продолжительность действия'))
    # ### end Alembic commands ###
