"""ref metabolism 2

Revision ID: 1d70d8ebc154
Revises: 5c58393959e9
Create Date: 2025-11-07 00:17:55.195766

"""
import os
import sys

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d70d8ebc154'
down_revision = '5c58393959e9'
branch_labels = None
depends_on = None

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', '..'))

from drug_search.infrastructure.database.models.drug import PydanticTypeList
from drug_search.core.schemas.drug_schemas import Pharmacokinetics


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('fun_facts', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('drugs', sa.Column('pharmacokinetics', PydanticTypeList(Pharmacokinetics), nullable=True, comment='JSON список фармакокинетики'))
    op.drop_column('drugs', 'absorption')
    op.drop_column('drugs', 'dosages_fun_facts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('dosages_fun_facts', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('drugs', sa.Column('absorption', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON список абсорбции {route, bioavailability, time_to_peak}'))
    op.drop_column('drugs', 'pharmacokinetics')
    op.drop_column('drugs', 'fun_facts')
    # ### end Alembic commands ###
