"""model fix1

Revision ID: 1e322be24453
Revises: 17782274653b
Create Date: 2025-09-12 00:55:27.464393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e322be24453'
down_revision = '17782274653b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
