"""add columns

Revision ID: 1e8dc45162f4
Revises: 498a6b302304
Create Date: 2025-10-07 14:47:36.886415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8dc45162f4'
down_revision = '498a6b302304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_search_requests', sa.Integer(), server_default='3', nullable=False, comment='Оставшиеся запросы на поиск препов'))
    op.add_column('users', sa.Column('allowed_question_requests', sa.Integer(), server_default='1', nullable=False, comment='Оставшиеся запросы на вопросы'))
    op.drop_column('users', 'allowed_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_requests', sa.INTEGER(), autoincrement=False, nullable=False, comment='Оставшиеся запросы сегодня'))
    op.drop_column('users', 'allowed_question_requests')
    op.drop_column('users', 'allowed_search_requests')
    # ### end Alembic commands ###
