"""сперма

Revision ID: 280276509122
Revises: 
Create Date: 2025-07-26 15:47:27.769415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280276509122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.Column('latin_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('dosages_fun_fact', sa.Text(), nullable=True),
    sa.Column('absorption', sa.String(length=100), nullable=True),
    sa.Column('metabolism', sa.Text(), nullable=True),
    sa.Column('elimination', sa.Text(), nullable=True),
    sa.Column('time_to_peak', sa.String(length=100), nullable=True),
    sa.Column('primary_action', sa.String(length=100), nullable=True),
    sa.Column('secondary_actions', sa.String(length=100), nullable=True),
    sa.Column('clinical_effects', sa.Text(), nullable=True),
    sa.Column('pathways_sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dosages_sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'name')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False, comment='telegram id'),
    sa.Column('username', sa.String(), nullable=False, comment='telegram username'),
    sa.Column('first_name', sa.String(), nullable=False, comment='telegram first name'),
    sa.Column('last_name', sa.String(), nullable=False, comment='telegram last name'),
    sa.Column('allowed_requests', sa.Integer(), nullable=False, comment='Количество разрешенных запросов'),
    sa.Column('used_requests', sa.Integer(), nullable=False, comment='Количество использованных запросов'),
    sa.Column('description', sa.Text(), nullable=False, comment="Каждые 10 запросов о пользователе обновляется его описание. Аля 'какой ты биофакер/химик/фармацевт?'"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_telegram_id', 'users', ['telegram_id'], unique=True)
    op.create_index('uq_users_username', 'users', ['username'], unique=True)
    op.create_table('allowed_drugs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'drug_id', 'id')
    )
    op.create_index('ix_allowed_drugs_user_id_drug_id', 'allowed_drugs', ['user_id', 'drug_id'], unique=False)
    op.create_table('drug_analogs',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('analog_name', sa.String(length=100), nullable=False, comment='аналог к основному drug'),
    sa.Column('percent', sa.Float(), nullable=False, comment='процент схожести'),
    sa.Column('difference', sa.String(length=100), nullable=False, comment='отличие от основного препа'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_analogs_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analog_name')
    )
    op.create_index(op.f('ix_drug_analogs_drug_id'), 'drug_analogs', ['drug_id'], unique=False)
    op.create_table('drug_combinations',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('combination_type', sa.String(length=10), nullable=False),
    sa.Column('substance', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('products', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_combinations_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_dosages',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=True, comment='parental/topical/other'),
    sa.Column('method', sa.String(length=30), nullable=True, comment='intravenous/intramuscular/eye_drops/skin/nasal/peroral/inhalation/rectal/vaginal'),
    sa.Column('per_time', sa.String(length=100), nullable=True),
    sa.Column('max_day', sa.String(length=100), nullable=True),
    sa.Column('per_time_weight_based', sa.String(length=100), nullable=True, comment='for peroral and intramuscular only'),
    sa.Column('max_day_weight_based', sa.String(length=100), nullable=True, comment='for peroral and intramuscular only'),
    sa.Column('onset', sa.String(length=100), nullable=True, comment="<Время начала действия (например, 'немедленно'). Только для intramuscular/intravenous/peroral>"),
    sa.Column('half_life', sa.String(length=100), nullable=True, comment='период полувыведения'),
    sa.Column('duration', sa.String(length=100), nullable=True, comment='продолжительность действия'),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_dosages_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'route', 'method', name='uq_drug_dosage')
    )
    op.create_table('drug_pathways',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('receptor', sa.String(length=100), nullable=False),
    sa.Column('binding_affinity', sa.String(length=50), nullable=True),
    sa.Column('affinity_description', sa.String(length=100), nullable=True),
    sa.Column('activation_type', sa.String(length=50), nullable=False),
    sa.Column('pathway', sa.String(length=100), nullable=True),
    sa.Column('effect', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_pathways_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'receptor', 'activation_type', name='uq_drug_pathway')
    )
    op.create_table('drug_prices',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('drug_brandname', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shop_url', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_prices_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_brandname')
    )
    op.create_table('drug_synonyms',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('synonym', sa.String(length=100), nullable=False, comment='одно из названий препарата на русском'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_synonyms_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'synonym', name='uq_drug_synonym'),
    sa.UniqueConstraint('synonym')
    )
    op.create_index('idx_drug_synonyms_lower', 'drug_synonyms', [sa.literal_column('lower(synonym)')], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_drug_synonyms_drug_id'), 'drug_synonyms', ['drug_id'], unique=False)
    op.create_index('trgm_drug_synonyms', 'drug_synonyms', ['synonym'], unique=False, postgresql_using='gin', postgresql_ops={'synonym': 'gin_trgm_ops'})
    op.create_table('user_request_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.String(), nullable=False, comment='запрос пользователя'),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_request_logs')
    op.drop_index('trgm_drug_synonyms', table_name='drug_synonyms', postgresql_using='gin', postgresql_ops={'synonym': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_drug_synonyms_drug_id'), table_name='drug_synonyms')
    op.drop_index('idx_drug_synonyms_lower', table_name='drug_synonyms', postgresql_using='btree')
    op.drop_table('drug_synonyms')
    op.drop_table('drug_prices')
    op.drop_table('drug_pathways')
    op.drop_table('drug_dosages')
    op.drop_table('drug_combinations')
    op.drop_index(op.f('ix_drug_analogs_drug_id'), table_name='drug_analogs')
    op.drop_table('drug_analogs')
    op.drop_index('ix_allowed_drugs_user_id_drug_id', table_name='allowed_drugs')
    op.drop_table('allowed_drugs')
    op.drop_index('uq_users_username', table_name='users')
    op.drop_index('uq_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_table('drugs')
    # ### end Alembic commands ###
