"""danger_drug_subscription

Revision ID: 2b95b702d08f
Revises: 6c85e5615992
Create Date: 2025-09-06 12:56:59.502788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b95b702d08f'
down_revision = '6c85e5615992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allowed_drugs', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('drugs', sa.Column('is_danger', sa.Boolean(), server_default='false', nullable=False, comment='опасный ли препарат (наркотик, стероид и т.д.)'))
    op.add_column('users', sa.Column('drug_subscription', sa.Boolean(), server_default='false', nullable=False, comment='подписка на запрещенку'))
    op.add_column('users', sa.Column('drug_subscription_end', sa.DateTime(), nullable=True, comment='окончание подписки на запрещенку'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'drug_subscription_end')
    op.drop_column('users', 'drug_subscription')
    op.drop_column('drugs', 'is_danger')
    op.drop_constraint(None, 'allowed_drugs', type_='foreignkey')
    # ### end Alembic commands ###
