"""del unique const

Revision ID: 343eb451aa59
Revises: 064b9e7bc3ea
Create Date: 2025-10-06 13:16:25.978192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343eb451aa59'
down_revision = '064b9e7bc3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allowed_drugs', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_constraint(op.f('uq_drug_pathway'), 'drug_pathways', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_drug_pathway'), 'drug_pathways', ['drug_id', 'receptor', 'activation_type'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'allowed_drugs', type_='foreignkey')
    # ### end Alembic commands ###
