"""модель исследований хуй

Revision ID: 39174154de2f
Revises: dd9cf1558a8d
Create Date: 2025-08-05 14:24:25.945944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39174154de2f'
down_revision = 'dd9cf1558a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drug_analogs_analog_name_key'), 'drug_analogs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('drug_analogs_analog_name_key'), 'drug_analogs', ['analog_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
