"""user co

Revision ID: 3d8c7b8e1910
Revises: 343eb451aa59
Create Date: 2025-10-07 02:31:37.824081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d8c7b8e1910'
down_revision = '343eb451aa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requests_last_refresh', sa.DateTime(), nullable=False, comment='последний сброс счётчика'))
    op.alter_column('users', 'subscription_end',
               existing_type=postgresql.TIMESTAMP(),
               comment='Конец подписки',
               existing_comment='окончание подписки',
               existing_nullable=True)
    op.alter_column('users', 'allowed_requests',
               existing_type=sa.INTEGER(),
               comment='Оставшиеся запросы сегодня',
               existing_comment='Количество разрешенных запросов',
               existing_nullable=False)
    op.alter_column('users', 'used_requests',
               existing_type=sa.INTEGER(),
               comment='Количество использованных запросов в общем',
               existing_comment='Количество использованных запросов',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'used_requests',
               existing_type=sa.INTEGER(),
               comment='Количество использованных запросов',
               existing_comment='Количество использованных запросов в общем',
               existing_nullable=False)
    op.alter_column('users', 'allowed_requests',
               existing_type=sa.INTEGER(),
               comment='Количество разрешенных запросов',
               existing_comment='Оставшиеся запросы сегодня',
               existing_nullable=False)
    op.alter_column('users', 'subscription_end',
               existing_type=postgresql.TIMESTAMP(),
               comment='окончание подписки',
               existing_comment='Конец подписки',
               existing_nullable=True)
    op.drop_column('users', 'requests_last_refresh')
    # ### end Alembic commands ###
