"""ref tokens

Revision ID: 42fe330e8a6a
Revises: 0da8fb4f995d
Create Date: 2025-11-18 02:31:25.809736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fe330e8a6a'
down_revision = '0da8fb4f995d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_tokens', sa.Integer(), server_default='0', nullable=False, comment='дополнительные токены (не сбрасываются)'))
    op.alter_column('users', 'allowed_tokens',
               existing_type=sa.INTEGER(),
               comment='Количество токенов',
               existing_comment='Оставшиеся запросы на поиск препов',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'allowed_tokens',
               existing_type=sa.INTEGER(),
               comment='Оставшиеся запросы на поиск препов',
               existing_comment='Количество токенов',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'additional_tokens')
    # ### end Alembic commands ###
