"""ref tokens

Revision ID: 448e9991b2b6
Revises: 1952d69f4cdb
Create Date: 2025-11-17 13:23:33.839152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448e9991b2b6'
down_revision = '1952d69f4cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_question_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_question_requests', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Оставшиеся запросы на вопросы'))
    # ### end Alembic commands ###
