"""simple mode

Revision ID: 4736f9c38e7c
Revises: de7f7b7ca5bb
Create Date: 2025-12-03 19:22:09.735562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4736f9c38e7c'
down_revision = 'de7f7b7ca5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allowed_drugs', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.add_column('users', sa.Column('simple_mode', sa.Boolean(), server_default='false', nullable=True, comment='Упрощенный режим'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'simple_mode')
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'allowed_drugs', type_='foreignkey')
    # ### end Alembic commands ###
