"""fix

Revision ID: 498a6b302304
Revises: 3d8c7b8e1910
Create Date: 2025-10-07 14:03:00.703767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498a6b302304'
down_revision = '3d8c7b8e1910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
