"""referrals

Revision ID: 4c61b5334fff
Revises: 4736f9c38e7c
Create Date: 2025-12-05 13:48:42.734655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c61b5334fff'
down_revision = '4736f9c38e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('referrer_telegram_id', sa.String(), nullable=False, comment='ID пригласившего'),
    sa.Column('referral_telegram_id', sa.String(), nullable=False, comment='ID приглашенного'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['referral_telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_telegram_id')
    )
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.add_column('users', sa.Column('got_free_tokens', sa.Boolean(), server_default='false', nullable=False, comment='получены бесплатные токены'))
    op.add_column('users', sa.Column('got_free_tokens_for_subscription', sa.Boolean(), server_default='false', nullable=False, comment='получены токены за подписки на каналы'))
    op.add_column('users', sa.Column('referred_by_telegram_id', sa.String(), nullable=True, comment='Telegram ID пользователя, который пригласил'))
    op.add_column('users', sa.Column('referrals_count', sa.Integer(), server_default='0', nullable=False, comment='количество рефералов'))
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               comment='описание юзера',
               existing_comment="Каждые 10 запросов о пользователе обновляется его описание. Аля 'какой ты биофакер/химик/фармацевт?'",
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by_telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               comment="Каждые 10 запросов о пользователе обновляется его описание. Аля 'какой ты биофакер/химик/фармацевт?'",
               existing_comment='описание юзера',
               existing_nullable=True)
    op.drop_column('users', 'referrals_count')
    op.drop_column('users', 'referred_by_telegram_id')
    op.drop_column('users', 'got_free_tokens_for_subscription')
    op.drop_column('users', 'got_free_tokens')
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('referrals')
    # ### end Alembic commands ###
