"""сперма

Revision ID: 4dc084cbf070
Revises: a6a68161eedb
Create Date: 2025-07-28 01:52:45.412534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc084cbf070'
down_revision = 'a6a68161eedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='telegram first name')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='telegram last name')
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment="Каждые 10 запросов о пользователе обновляется его описание. Аля 'какой ты биофакер/химик/фармацевт?'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment="Каждые 10 запросов о пользователе обновляется его описание. Аля 'какой ты биофакер/химик/фармацевт?'")
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='telegram last name')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='telegram first name')
    # ### end Alembic commands ###
