"""fix

Revision ID: 4f13ba10519e
Revises: 5d5a1045fe3a
Create Date: 2025-09-20 00:12:04.053759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f13ba10519e'
down_revision = '5d5a1045fe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_drug_synonym'), 'drug_synonyms', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_drug_synonym'), 'drug_synonyms', ['drug_id', 'synonym'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
