"""ref metabolism

Revision ID: 5c58393959e9
Revises: e12186fc4db4
Create Date: 2025-11-05 21:48:04.233387

"""
import os
import sys

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', '..'))

from drug_search.infrastructure.database.models.drug import PydanticTypeList
from drug_search.core.schemas.drug_schemas import MetabolismPhase, EliminationInfo, AbsorptionInfo


# revision identifiers, used by Alembic.
revision = '5c58393959e9'
down_revision = 'e12186fc4db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_prices', sa.Column('drug_brand', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('drug_prices_drug_brandname_key'), 'drug_prices', type_='unique')
    op.create_unique_constraint('uq_drug_prices_brand', 'drug_prices', ['drug_brand'])
    op.drop_column('drug_prices', 'drug_brandname')

    # Сначала преобразуем данные в валидный JSON
    connection = op.get_bind()

    # Для absorption - преобразуем в пустой массив, если данные невалидны
    connection.execute(text("""
        UPDATE drugs 
        SET absorption = '[]'::json 
        WHERE absorption IS NULL OR absorption !~ '^\\[.*\\]$'
    """))

    # Для metabolism - преобразуем в пустой массив, если данные невалидны
    connection.execute(text("""
        UPDATE drugs 
        SET metabolism = '[]'::json 
        WHERE metabolism IS NULL OR metabolism !~ '^\\[.*\\]$'
    """))

    # Для elimination - преобразуем в пустой массив, если данные невалидны
    connection.execute(text("""
        UPDATE drugs 
        SET elimination = '[]'::json 
        WHERE elimination IS NULL OR elimination !~ '^\\[.*\\]$'
    """))

    # Теперь меняем тип с использованием USING
    op.alter_column('drugs', 'absorption',
               existing_type=sa.TEXT(),
               type_=PydanticTypeList(AbsorptionInfo),
               comment='JSON список абсорбции {route, bioavailability, time_to_peak}',
               existing_nullable=True,
               postgresql_using='absorption::json')

    op.alter_column('drugs', 'metabolism',
               existing_type=sa.TEXT(),
               type_=PydanticTypeList(MetabolismPhase),
               comment='JSON список фаз метаболизма {phase, process, result}',
               existing_nullable=True,
               postgresql_using='metabolism::json')

    op.alter_column('drugs', 'elimination',
               existing_type=sa.TEXT(),
               type_=PydanticTypeList(EliminationInfo),
               comment='JSON список выведения {excrement_type, output_percent}',
               existing_nullable=True,
               postgresql_using='elimination::json')

    op.drop_column('drugs', 'time_to_peak')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('time_to_peak', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # Преобразуем JSON обратно в TEXT
    connection = op.get_bind()

    connection.execute(text("""
        UPDATE drugs 
        SET absorption = absorption::text
        WHERE absorption IS NOT NULL
    """))

    connection.execute(text("""
        UPDATE drugs 
        SET metabolism = metabolism::text
        WHERE metabolism IS NOT NULL
    """))

    connection.execute(text("""
        UPDATE drugs 
        SET elimination = elimination::text
        WHERE elimination IS NOT NULL
    """))

    op.alter_column('drugs', 'elimination',
               existing_type=PydanticTypeList(EliminationInfo),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='JSON список выведения {excrement_type, output_percent}',
               existing_nullable=True,
               postgresql_using='elimination::text')

    op.alter_column('drugs', 'metabolism',
               existing_type=PydanticTypeList(MetabolismPhase),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='JSON список фаз метаболизма {phase, process, result}',
               existing_nullable=True,
               postgresql_using='metabolism::text')

    op.alter_column('drugs', 'absorption',
               existing_type=PydanticTypeList(AbsorptionInfo),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='JSON список абсорбции {route, bioavailability, time_to_peak}',
               existing_nullable=True,
               postgresql_using='absorption::text')

    op.add_column('drug_prices', sa.Column('drug_brandname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('uq_drug_prices_brand', 'drug_prices', type_='unique')
    op.create_unique_constraint(op.f('drug_prices_drug_brandname_key'), 'drug_prices', ['drug_brandname'])
    op.drop_column('drug_prices', 'drug_brand')
    # ### end Alembic commands ###