"""rel fix

Revision ID: 5d5a1045fe3a
Revises: 058b34c6fc72
Create Date: 2025-09-19 00:49:05.755461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5a1045fe3a'
down_revision = '058b34c6fc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
