"""sosal?

Revision ID: 6c85e5615992
Revises: 111ee4c98a4f
Create Date: 2025-08-19 17:40:05.910147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c85e5615992'
down_revision = '111ee4c98a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_drugs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'drug_id', 'id')
    )
    op.create_index('ix_allowed_drugs_user_id_drug_id', 'allowed_drugs', ['user_id', 'drug_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_allowed_drugs_user_id_drug_id', table_name='allowed_drugs')
    op.drop_table('allowed_drugs')
    # ### end Alembic commands ###
