"""fix limits

Revision ID: 702b0d39b514
Revises: 4f13ba10519e
Create Date: 2025-09-20 17:23:38.976031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702b0d39b514'
down_revision = '4f13ba10519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drugs', 'classification',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drugs', 'classification',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
