"""empty message

Revision ID: 8600050e227d
Revises: d4e0b7bf6622
Create Date: 2025-12-17 19:13:04.011331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8600050e227d'
down_revision = 'd4e0b7bf6622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.drop_constraint(op.f('payment_logs_package_key_key'), 'payment_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('payment_logs_package_key_key'), 'payment_logs', ['package_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
