"""payment model

Revision ID: 870d9897bc35
Revises: 97adac9dd9c1
Create Date: 2025-12-17 19:04:31.529691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870d9897bc35'
down_revision = '97adac9dd9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_key', sa.String(length=100), nullable=False, comment='Ключ платежа (пакета)'),
    sa.Column('payment_name', sa.String(length=100), nullable=False, comment='Название платежа'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Сумма платежа в рублях'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id'),
    sa.UniqueConstraint('package_key')
    )
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('payment_logs')
    # ### end Alembic commands ###
