"""fix column research 2

Revision ID: 885d39bf4706
Revises: a48f893daab8
Create Date: 2025-09-13 02:23:26.939766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885d39bf4706'
down_revision = 'a48f893daab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_analogs', 'difference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='отличие от основного препа',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_analogs', 'difference',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_comment='отличие от основного препа',
               existing_nullable=False)
    # ### end Alembic commands ###
