"""fix dosages unique constraits

Revision ID: 903166116471
Revises: 3e48b7476e69
Create Date: 2025-12-08 17:41:30.457443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903166116471'
down_revision = '3e48b7476e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_drug_dosage'), 'drug_dosages', type_='unique')
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_drug_dosage'), 'drug_dosages', ['drug_id', 'route', 'method'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
