"""payment model

Revision ID: 97adac9dd9c1
Revises: 6d2558de7536
Create Date: 2025-12-17 18:51:09.956059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97adac9dd9c1'
down_revision = '6d2558de7536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_researchs', 'interest',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
