"""сперма

Revision ID: a6a68161eedb
Revises: 280276509122
Create Date: 2025-07-27 18:14:25.276525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a68161eedb'
down_revision = '280276509122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allowed_drugs', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.alter_column('drugs', 'primary_action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('drugs', 'secondary_actions',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drugs', 'secondary_actions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drugs', 'primary_action',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'allowed_drugs', type_='foreignkey')
    # ### end Alembic commands ###
