"""модель исследований хуй

Revision ID: a9d6d037f4c8
Revises: 39174154de2f
Create Date: 2025-08-05 14:52:59.363249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d6d037f4c8'
down_revision = '39174154de2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_researchs', sa.Column('publication_date', sa.Date(), nullable=False))
    op.drop_column('drug_researchs', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_researchs', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('drug_researchs', 'publication_date')
    # ### end Alembic commands ###
