"""model fix2

Revision ID: be54babd2f86
Revises: 1e322be24453
Create Date: 2025-09-12 00:56:34.115289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be54babd2f86'
down_revision = '1e322be24453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_drug_researchs_doi'), table_name='drug_researchs')
    op.create_index('idx_drug_researches_doi', 'drug_researchs', ['doi'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_drug_researches_doi', table_name='drug_researchs')
    op.create_index(op.f('idx_drug_researchs_doi'), 'drug_researchs', ['doi'], unique=True)
    # ### end Alembic commands ###
