"""модель исследований

Revision ID: dd9cf1558a8d
Revises: 4dc084cbf070
Create Date: 2025-08-05 13:49:59.965385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9cf1558a8d'
down_revision = '4dc084cbf070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_researchs',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=100), nullable=False),
    sa.Column('doi', sa.String(length=50), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('study_type', sa.String(length=50), nullable=True),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='fk_drug_researchs_drug_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index('idx_drug_researchs_doi', 'drug_researchs', ['doi'], unique=True)
    op.create_index(op.f('ix_drug_researchs_drug_id'), 'drug_researchs', ['drug_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drug_researchs_drug_id'), table_name='drug_researchs')
    op.drop_index('idx_drug_researchs_doi', table_name='drug_researchs')
    op.drop_table('drug_researchs')
    # ### end Alembic commands ###
