"""drug model ref

Revision ID: e12186fc4db4
Revises: 1e8dc45162f4
Create Date: 2025-11-03 23:45:49.785058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e12186fc4db4'
down_revision = '1e8dc45162f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_pathways', 'receptor',
               existing_type=sa.VARCHAR(length=100),
               comment='название рецептора',
               existing_nullable=False)
    op.alter_column('drug_pathways', 'binding_affinity',
               existing_type=sa.VARCHAR(length=200),
               comment='сила связывания',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'affinity_description',
               existing_type=sa.VARCHAR(length=200),
               comment='сила связывания',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'activation_type',
               existing_type=sa.VARCHAR(length=200),
               comment='тип активации',
               existing_nullable=False)
    op.alter_column('drug_pathways', 'pathway',
               existing_type=sa.VARCHAR(length=200),
               comment='сигнальный путь',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'effect',
               existing_type=sa.VARCHAR(length=200),
               comment='физиологический эффект',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'note',
               existing_type=sa.TEXT(),
               comment='дополнительные примечания',
               existing_nullable=True)
    op.add_column('drugs', sa.Column('fact', sa.Text(), nullable=True))
    op.add_column('drugs', sa.Column('dosages_fun_facts', sa.ARRAY(sa.Text()), nullable=True))
    op.alter_column('drugs', 'pathways_sources',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True)
    op.alter_column('drugs', 'dosage_sources',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True)
    op.drop_column('drugs', 'fun_fact')
    op.drop_column('drugs', 'dosages_fun_fact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('dosages_fun_fact', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('drugs', sa.Column('fun_fact', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('drugs', 'dosage_sources',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('drugs', 'pathways_sources',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('drugs', 'dosages_fun_facts')
    op.drop_column('drugs', 'fact')
    op.alter_column('drug_pathways', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='дополнительные примечания',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'effect',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='физиологический эффект',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'pathway',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='сигнальный путь',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'activation_type',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='тип активации',
               existing_nullable=False)
    op.alter_column('drug_pathways', 'affinity_description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='сила связывания',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'binding_affinity',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='сила связывания',
               existing_nullable=True)
    op.alter_column('drug_pathways', 'receptor',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='название рецептора',
               existing_nullable=False)
    # ### end Alembic commands ###
