"""fix column research 3

Revision ID: f57367a5ca41
Revises: 885d39bf4706
Create Date: 2025-09-13 02:28:24.933856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f57367a5ca41'
down_revision = '885d39bf4706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_combinations', 'sources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_combinations', sa.Column('sources', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
